# Generated by Django 4.2 on 2025-08-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
